import type { AssetCriticality } from "@/lib/database.types";

export const VENDOR_CATEGORIES = [
  "hosting",
  "cdn",
  "analytics",
  "payments",
  "identity",
  "communications",
  "security",
  "cms",
  "ads",
  "fonts",
  "maps",
  "devtools",
  "other",
] as const;

export type VendorCategory = (typeof VENDOR_CATEGORIES)[number];

export type VendorDef = {
  id: string;
  name: string;
  category: VendorCategory;
  criticality: AssetCriticality;
  processesData: boolean;
  connectsToProduction: boolean;
  dataClasses: string[];
  html: string[];
  headers?: { name: string; value?: string }[];
  packages?: string[];
  tech?: string[];
};

export const VENDOR_CATALOG: VendorDef[] = [
  {
    id: "cloudflare",
    name: "Cloudflare",
    category: "cdn",
    criticality: "high",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["traffic", "ip"],
    html: ["cdnjs.cloudflare.com", "cloudflareinsights.com", "challenges.cloudflare.com"],
    headers: [{ name: "cf-ray" }, { name: "server", value: "cloudflare" }],
    tech: ["Cloudflare"],
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "hosting",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["application", "logs"],
    html: ["vercel.live", "_vercel"],
    headers: [{ name: "x-vercel-id" }, { name: "x-vercel-cache" }],
    packages: ["@vercel/analytics", "@vercel/speed-insights"],
    tech: ["Vercel"],
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "hosting",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["application"],
    html: ["netlify.app", "netlify.com"],
    headers: [{ name: "x-nf-request-id" }],
  },
  {
    id: "aws",
    name: "Amazon Web Services",
    category: "hosting",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["application", "customer"],
    html: ["cloudfront.net", "amazonaws.com", "awsstatic.com"],
    headers: [{ name: "x-amz-cf-id" }, { name: "x-amz-request-id" }],
    packages: ["aws-sdk", "@aws-sdk/client-s3", "@aws-sdk/client-ses"],
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    category: "hosting",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["application"],
    html: ["storage.googleapis.com", "appspot.com", "run.app"],
    packages: ["@google-cloud/storage", "firebase", "firebase-admin"],
  },
  {
    id: "firebase",
    name: "Firebase",
    category: "hosting",
    criticality: "high",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["customer", "auth"],
    html: ["firebaseio.com", "firebaseapp.com", "firebase.google.com"],
    packages: ["firebase", "firebase-admin"],
  },
  {
    id: "supabase",
    name: "Supabase",
    category: "hosting",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["customer", "auth"],
    html: ["supabase.co", "supabase.com"],
    packages: ["@supabase/supabase-js", "@supabase/ssr"],
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "cms",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["customer", "payments"],
    html: ["cdn.shopify.com", "myshopify.com", "shopify.com"],
    tech: ["Shopify"],
  },
  {
    id: "wordpress",
    name: "WordPress",
    category: "cms",
    criticality: "high",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["content", "customer"],
    html: ["wp-content", "wp-includes", "wordpress.com"],
    tech: ["WordPress"],
  },
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["payments", "customer"],
    html: ["js.stripe.com", "checkout.stripe.com", "stripe.com"],
    packages: ["stripe", "@stripe/stripe-js", "@stripe/react-stripe-js"],
  },
  {
    id: "paypal",
    name: "PayPal",
    category: "payments",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["payments", "customer"],
    html: ["paypal.com", "paypalobjects.com"],
    packages: ["@paypal/checkout-server-sdk"],
  },
  {
    id: "paystack",
    name: "Paystack",
    category: "payments",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["payments", "customer"],
    html: ["js.paystack.co", "paystack.co", "paystack.com"],
    packages: ["paystack"],
  },
  {
    id: "flutterwave",
    name: "Flutterwave",
    category: "payments",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["payments", "customer"],
    html: ["flutterwave.com", "checkout.flutterwave.com"],
    packages: ["flutterwave-node-v3"],
  },
  {
    id: "mpesa",
    name: "M-Pesa",
    category: "payments",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["payments", "customer"],
    html: ["safaricom.co.ke", "m-pesa"],
  },
  {
    id: "pesapal",
    name: "Pesapal",
    category: "payments",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["payments", "customer"],
    html: ["pesapal.com"],
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    category: "analytics",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour", "ip"],
    html: [
      "google-analytics.com",
      "googletagmanager.com",
      "gtag/js",
      "analytics.google.com",
    ],
    packages: ["@next/third-parties"],
  },
  {
    id: "hotjar",
    name: "Hotjar",
    category: "analytics",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour", "session"],
    html: ["static.hotjar.com", "hotjar.com"],
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "analytics",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour"],
    html: ["cdn.mxpnl.com", "mixpanel.com", "api.mixpanel.com"],
    packages: ["mixpanel", "mixpanel-browser"],
  },
  {
    id: "segment",
    name: "Segment",
    category: "analytics",
    criticality: "high",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour", "customer"],
    html: ["cdn.segment.com", "api.segment.io"],
    packages: ["analytics.js", "@segment/analytics-next"],
  },
  {
    id: "posthog",
    name: "PostHog",
    category: "analytics",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour"],
    html: ["posthog.com", "us.i.posthog.com", "eu.i.posthog.com"],
    packages: ["posthog-js", "posthog-node"],
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "devtools",
    criticality: "medium",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["errors", "session"],
    html: ["browser.sentry-cdn.com", "sentry.io", "ingest.sentry.io"],
    packages: ["@sentry/nextjs", "@sentry/node", "@sentry/browser"],
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "devtools",
    criticality: "high",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["logs", "session"],
    html: ["datadoghq.com", "datadog-browser-agent"],
    packages: ["dd-trace", "@datadog/browser-rum"],
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "communications",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["customer", "support"],
    html: ["widget.intercom.io", "js.intercomcdn.com", "intercom.io"],
    packages: ["@intercom/messenger-js-sdk"],
  },
  {
    id: "hubspot",
    name: "HubSpot",
    category: "communications",
    criticality: "high",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["customer"],
    html: ["js.hs-scripts.com", "js.hsforms.net", "hubspot.com"],
  },
  {
    id: "zendesk",
    name: "Zendesk",
    category: "communications",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["customer", "support"],
    html: ["static.zdassets.com", "zendesk.com"],
  },
  {
    id: "crisp",
    name: "Crisp",
    category: "communications",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["customer", "support"],
    html: ["client.crisp.chat", "crisp.chat"],
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "identity",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["auth", "customer"],
    html: ["auth0.com", "cdn.auth0.com"],
    packages: ["auth0", "@auth0/nextjs-auth0"],
  },
  {
    id: "clerk",
    name: "Clerk",
    category: "identity",
    criticality: "critical",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["auth", "customer"],
    html: ["clerk.accounts.dev", "clerk.com", "clerk.dev"],
    packages: ["@clerk/nextjs", "@clerk/clerk-sdk-node"],
  },
  {
    id: "recaptcha",
    name: "Google reCAPTCHA",
    category: "security",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour", "ip"],
    html: ["www.google.com/recaptcha", "www.gstatic.com/recaptcha", "recaptcha"],
  },
  {
    id: "turnstile",
    name: "Cloudflare Turnstile",
    category: "security",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour", "ip"],
    html: ["challenges.cloudflare.com/turnstile"],
  },
  {
    id: "meta-pixel",
    name: "Meta Pixel",
    category: "ads",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour", "ads"],
    html: ["connect.facebook.net", "facebook.net/en_US/fbevents"],
  },
  {
    id: "linkedin-insight",
    name: "LinkedIn Insight",
    category: "ads",
    criticality: "low",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour", "ads"],
    html: ["snap.licdn.com", "linkedin.com/li.lms-analytics"],
  },
  {
    id: "google-fonts",
    name: "Google Fonts",
    category: "fonts",
    criticality: "low",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["ip"],
    html: ["fonts.googleapis.com", "fonts.gstatic.com"],
  },
  {
    id: "mapbox",
    name: "Mapbox",
    category: "maps",
    criticality: "medium",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["location"],
    html: ["api.mapbox.com", "mapbox.com"],
    packages: ["mapbox-gl"],
  },
  {
    id: "youtube",
    name: "YouTube",
    category: "other",
    criticality: "low",
    processesData: true,
    connectsToProduction: false,
    dataClasses: ["behaviour"],
    html: ["youtube.com/embed", "youtube-nocookie.com", "ytimg.com"],
  },
  {
    id: "jsdelivr",
    name: "jsDelivr",
    category: "cdn",
    criticality: "low",
    processesData: false,
    connectsToProduction: false,
    dataClasses: [],
    html: ["cdn.jsdelivr.net"],
  },
  {
    id: "unpkg",
    name: "unpkg",
    category: "cdn",
    criticality: "low",
    processesData: false,
    connectsToProduction: false,
    dataClasses: [],
    html: ["unpkg.com"],
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "communications",
    criticality: "high",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["customer", "messages"],
    html: ["twilio.com"],
    packages: ["twilio"],
  },
  {
    id: "resend",
    name: "Resend",
    category: "communications",
    criticality: "high",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["customer", "email"],
    html: ["resend.com"],
    packages: ["resend"],
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "devtools",
    criticality: "high",
    processesData: true,
    connectsToProduction: true,
    dataClasses: ["prompts", "customer"],
    html: ["api.openai.com", "chatgpt.com"],
    packages: ["openai"],
  },
];

export const VENDOR_CATEGORY_LABELS: Record<VendorCategory, string> = {
  hosting: "Hosting",
  cdn: "CDN / edge",
  analytics: "Analytics",
  payments: "Payments",
  identity: "Identity",
  communications: "Communications",
  security: "Security",
  cms: "CMS / commerce",
  ads: "Advertising",
  fonts: "Fonts",
  maps: "Maps",
  devtools: "Observability",
  other: "Other",
};
