import type { ConnectorDef, DataDomain } from "./types";

export const CONNECTOR_TIER_LABELS = {
  authoritative: "Authoritative",
  commercial: "Commercial",
  public_web: "Public web",
  customer: "Customer-authorised",
} as const;

export const CONNECTOR_STATUS_LABELS = {
  connected: "Connected",
  available: "Available",
  license_required: "Licence required",
  customer_consent_required: "Customer consent required",
  not_available: "Not available",
  unverified: "Unverified",
} as const;

export const DATA_DOMAIN_LABELS: Record<DataDomain, string> = {
  identity: "Corporate identity",
  ownership: "Directors / ownership",
  licensing: "Regulatory / licensing",
  digital: "Web / digital footprint",
  documents: "Public documents",
  adverse: "Adverse information",
  relationships: "Relationship mapping",
  customer_vault: "Customer-uploaded evidence",
  finance: "Authorised financial artefacts",
};

export const KENYA_CONNECTORS: ConnectorDef[] = [
  {
    id: "ke-website",
    name: "Company website",
    country: "KE",
    authority: "The company's own public site",
    tier: "public_web",
    access: "public_permissioned",
    status: "available",
    domains: ["identity", "digital", "relationships"],
    reliability: 62,
    refresh: "On scan",
    cost: "Own infra. No licence.",
    permission: "Public HTTPS pages the company publishes.",
    note: "A website is a claim surface, not a CR12. VERIQ reads it as OBSERVED copy.",
    sourceUrl: null,
  },
  {
    id: "ke-wikidata",
    name: "Wikidata official website (P856)",
    country: "KE",
    authority: "Wikidata",
    tier: "public_web",
    access: "api",
    status: "available",
    domains: ["identity"],
    reliability: 70,
    refresh: "On name resolve",
    cost: "Free API.",
    permission: "Wikimedia terms. Not a company extract.",
    note: "Used only to resolve a public hostname from a name.",
    sourceUrl: "https://www.wikidata.org",
  },
  {
    id: "ke-dns-tls",
    name: "DNS, TLS and certificate transparency",
    country: "KE",
    authority: "Public DNS / crt.sh",
    tier: "public_web",
    access: "public_permissioned",
    status: "available",
    domains: ["digital"],
    reliability: 88,
    refresh: "On scan",
    cost: "Free public resolvers.",
    permission: "Public DNS and CT logs.",
    note: "Hostnames and certificates. Not ownership.",
    sourceUrl: "https://crt.sh",
  },
  {
    id: "ke-github",
    name: "GitHub public profile",
    country: "KE",
    authority: "GitHub",
    tier: "public_web",
    access: "api",
    status: "available",
    domains: ["digital", "relationships"],
    reliability: 80,
    refresh: "On scan",
    cost: "Free public API. Org OAuth later.",
    permission: "Public repositories, or customer-authorised org token.",
    note: "Secret values are never stored. Login is not guessed from the company name.",
    sourceUrl: "https://docs.github.com/en/rest",
  },
  {
    id: "ke-customer-vault",
    name: "Customer evidence vault",
    country: "KE",
    authority: "The reviewing institution / the company",
    tier: "customer",
    access: "customer_authorised",
    status: "customer_consent_required",
    domains: ["customer_vault", "ownership", "licensing", "documents", "finance"],
    reliability: 92,
    refresh: "When an artefact is uploaded",
    cost: "No data fee. The bank or investor already holds the file.",
    permission: "Upload or system connect by the customer. VERIQ does not fetch the vault.",
    note: "CR12, licence, accounts, bank statements, tax files, contracts. Today: upload. Tomorrow: core-banking / data-room connect.",
    sourceUrl: null,
  },
  {
    id: "ke-brs",
    name: "Kenya company registry (BRS / eCitizen)",
    country: "KE",
    authority: "Business Registration Service",
    tier: "authoritative",
    access: "partnership",
    status: "customer_consent_required",
    domains: ["identity", "ownership"],
    reliability: 96,
    refresh: "On official extract",
    cost: "Partnership or per-extract. Do not budget a scrape. Banks already collect CR12.",
    permission: "Official API, licensed feed, or customer-supplied extract. Scraping eCitizen is refused.",
    note: "Directors, shareholders, status. get_directors() reads an uploaded CR12 today, a BRS API tomorrow. The engine does not change.",
    sourceUrl: "https://brs.go.ke",
  },
  {
    id: "ke-licence-lists",
    name: "CBK / CMA / IRA published licence lists",
    country: "KE",
    authority: "Central Bank of Kenya, Capital Markets Authority, Insurance Regulatory Authority",
    tier: "authoritative",
    access: "public_permissioned",
    status: "available",
    domains: ["licensing"],
    reliability: 90,
    refresh: "When a published list is ingested under licence/ToS",
    cost: "Engineering + terms of the published list. Not a live licence API.",
    permission: "Official published lists only. VERIQ does not scrape private regulator portals.",
    note: "Whether this company is on a list stays UNKNOWN until a connector is authorised or a licence is uploaded.",
    sourceUrl: "https://www.centralbank.go.ke",
  },
  {
    id: "ke-kenya-law",
    name: "Kenya Law / Kenya Gazette",
    country: "KE",
    authority: "National Council for Law Reporting",
    tier: "authoritative",
    access: "public_permissioned",
    status: "available",
    domains: ["adverse", "documents"],
    reliability: 86,
    refresh: "When a permissioned ingest exists",
    cost: "Engineering against published judgments and Gazette notices. Watch ToS and bulk use.",
    permission: "Public legal texts. Not a finding of guilt from a name match alone.",
    note: "Litigation and Gazette facts are UNKNOWN until this connector is live. Name-match false positives stay labelled.",
    sourceUrl: "https://kenyalaw.org",
  },
  {
    id: "ke-ppip",
    name: "Public procurement notices (PPIP / PPRA)",
    country: "KE",
    authority: "Public Procurement Regulatory Authority",
    tier: "authoritative",
    access: "public_permissioned",
    status: "available",
    domains: ["documents", "relationships", "adverse"],
    reliability: 84,
    refresh: "When a permissioned ingest exists",
    cost: "Engineering. Do not scrape PPIP until access is authorised.",
    permission: "Published tender and award notices.",
    note: "Awards and debarment stay UNKNOWN. This is not a finding that a tender was irregular.",
    sourceUrl: "https://www.ppra.go.ke",
  },
  {
    id: "ke-sanctions",
    name: "UN / OFAC / UK consolidated sanctions lists",
    country: "KE",
    authority: "UN, OFAC, UK OFSI",
    tier: "authoritative",
    access: "public_permissioned",
    status: "available",
    domains: ["adverse"],
    reliability: 88,
    refresh: "When list files are ingested",
    cost: "Free official downloads. Matching cost is false-positive review, not the file.",
    permission: "Official published lists. A name collision is not a sanction hit.",
    note: "Not connected yet. VERIQ will not invent a PEP or a designation.",
    sourceUrl: "https://sanctionssearch.ofac.treas.gov",
  },
  {
    id: "ke-credit-bureau",
    name: "Licensed credit bureau",
    country: "KE",
    authority: "Metropol / TransUnion / Creditinfo (licensed under CBK)",
    tier: "commercial",
    access: "api",
    status: "license_required",
    domains: ["ownership", "adverse"],
    reliability: 91,
    refresh: "Per lookup",
    cost: "Commercial per-lookup or enterprise feed. Do not scrape. Partner, do not compete on raw files.",
    permission: "Bureau licence + customer consent / permissible purpose.",
    note: "Credit and director files stay LICENSE REQUIRED. VERIQ is the intelligence layer, not a bureau clone.",
    sourceUrl: null,
  },
  {
    id: "ke-linkedin",
    name: "LinkedIn",
    country: "KE",
    authority: "LinkedIn",
    tier: "public_web",
    access: "refused",
    status: "not_available",
    domains: ["relationships", "ownership"],
    reliability: 0,
    refresh: "Never",
    cost: "Not a source. Official API is restricted; scraping is refused.",
    permission: "None. VERIQ will not scrape LinkedIn.",
    note: "Headcount from LinkedIn stays UNKNOWN. Upload payroll or attest a band.",
    sourceUrl: null,
  },
];

export function connectorsForCountry(country: string) {
  const code = country.toUpperCase();
  const rows = KENYA_CONNECTORS.filter((row) => row.country === code);
  return rows.length ? rows : KENYA_CONNECTORS.filter((row) => row.country === "KE");
}
